###############################################################################
#
# 2020_leaf_invest_weather --- gs_sample.csv
#
###############################################################################
[2020_leaf_invest_weather]
git-tree-sha1 = "457f3a77001a4801f9344bb05666267484b36edf"
lazy = true

    [[2020_leaf_invest_weather.download]]
    sha256 = "5073edf5b7a3713f65ba0a2ee6801323570250ce6e46faa7cd45bb84fda487c5"
    url = "https://github.com/Yujie-W/ResearchArtifacts/raw/wyujie/2020_leaf_invest/2020_leaf_invest_weather.tar.gz"

[land_model_spectrum]
git-tree-sha1 = "5f60e2aba2640828adf889f3070d064b602386ed"
lazy = true

    [[land_model_spectrum.download]]
    sha256 = "d9e93d13529ec35872a4849d346efd94580788a8e62dfc1c65e3c2f31c582589"
    url = "ftp://fluo.gps.caltech.edu/XYZT_CLIMA_LUT/LandModel/land_model_spectrum.tar.gz"
    [[land_model_spectrum.download]]
    sha256 = "d9e93d13529ec35872a4849d346efd94580788a8e62dfc1c65e3c2f31c582589"
    url = "https://github.com/Yujie-W/ResearchArtifacts/raw/wyujie/CliMA_LUT/land_model_spectrum.tar.gz"
