###############################################################################
#
# 2020_leaf_invest_weather --- gs_sample.csv
#
###############################################################################
[2020_leaf_invest_weather]
git-tree-sha1 = "457f3a77001a4801f9344bb05666267484b36edf"
lazy = true

    [[2020_leaf_invest_weather.download]]
    sha256 = "5073edf5b7a3713f65ba0a2ee6801323570250ce6e46faa7cd45bb84fda487c5"
    url = "https://github.com/Yujie-W/ResearchArtifacts/raw/wyujie/2020_leaf_invest/2020_leaf_invest_weather.tar.gz"

[land_model_spectrum]
git-tree-sha1 = "ad248def1185cce69f626613dd1f70333a8290a6"
lazy = true

    [[land_model_spectrum.download]]
    sha256 = "cd260824a471900a88004818bb9ea0b77e6255213ef2a6648668659268ed494d"
    url = "ftp://fluo.gps.caltech.edu/XYZT_CLIMA_LUT/LandModel/land_model_spectrum.tar.gz"
    [[land_model_spectrum.download]]
    sha256 = "cd260824a471900a88004818bb9ea0b77e6255213ef2a6648668659268ed494d"
    url = "https://github.com/Yujie-W/ResearchArtifacts/raw/wyujie/CliMA_LUT/land_model_spectrum.tar.gz"
