status = [
    "clean-notebooks",
    "docs-build",
    "macos-latest",
    "ubuntu-latest",
    "windows-latest",
    "version-test"
]
delete_merged_branches = true
timeout_sec = 86400
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
