status = [
  "clean-notebooks",
  "docs-build",
  "linux-test",
  "macos-test",
  "windows-test"
]
delete_merged_branches = true
timeout_sec = 86400
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
