name = "Land"
uuid = "27e3c115-2cb8-4114-b7a5-cd9f011f9dcc"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WaterPhysics = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"

[compat]
DiffEqOperators = "4.34.0"
OrdinaryDiffEq = "6.28.1"
WaterPhysics = "0.1.3"
julia = "1.7"
