name = "WaterPhysics"
uuid = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.2"

[deps]
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CLIMAParameters = "0.1.6"
DocStringExtensions = "0.8"
PkgUtility = "0.1"
julia = "1.3"
