name = "ClimaCache"
uuid = "781d2db2-48ae-11ec-81d3-0242ac130003"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DocStringExtensions = "0.8.6"
julia = "1.6"
