name = "CanopyRadiativeTransfer"
uuid = "7d47ec4b-9a51-4ee3-9fcc-f90243bd7361"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.0"

[deps]
ClimaCache = "781d2db2-48ae-11ec-81d3-0242ac130003"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ClimaCache = "0.3.2"
DocStringExtensions = "0.8.6, 0.9"
julia = "1.6"
