name = "EmeraldConstants"
uuid = "f1e47f7f-56cf-4a63-9b2b-695e95ad7a29"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DocStringExtensions = "0.8.6, 0.9.0"
julia = "1.7"
