name = "WaterPhysics"
uuid = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.5"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EmeraldConstants = "f1e47f7f-56cf-4a63-9b2b-695e95ad7a29"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DocStringExtensions = "0.8.6, 0.9.0"
EmeraldConstants = "0.1.0"
PkgUtility = "0.1.9, 0.2.0"
julia = "1.7"
