name = "EmeraldOptics"
uuid = "6ff41c79-fbfa-4eb2-86fa-4dd17bfb78a4"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.0"

[deps]
EmeraldConstants = "f1e47f7f-56cf-4a63-9b2b-695e95ad7a29"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
EmeraldConstants = "0.1.0"
julia = "1.6"
